# Site settings
title: The Blackburn Foundation
email: info@blackburnfoundation.org
description: "Committed to promoting higher education and community development."
baseurl: ""
url: "https://blackburnfoundation.org"
social:
  twitter: blackburnf
  facebook: blackburnfoundation

twitter_username: blackburnf

header_pages:
 - about.md
 - blog.md
 - donate.md
 - volunteer.md

google_analytics: "UA-2869148-4"

# Build settings
theme: minima
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-sitemap

include: [".well-known"]

exclude:
  - old

sass:
  style: compressed
