# Site settings
title: The Blackburn Foundation
email: info@blackburnfoundation.org
description: "Committed to promoting higher education and community development."
baseurl: ""
url: "http://blackburnfoundation.org"
social:
  twitter: blackburnf
  facebook: blackburnfoundation

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap
